name: unais_academy_prototype
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  lottie: ^1.2.2
  flutter_native_splash: ^2.1.0
  google_fonts: ^2.3.1
  sliding_sheet: ^0.5.2
  change_app_package_name: ^1.0.0
  

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true

dev_dependencies:
  flutter_app_name:
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "Unais Academy"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
      - family: Helvatica
        fonts:
          - asset: assets/fonts/Helvetica-Font/Helvetica-Bold.ttf
      - family: Helvatica_lite
        fonts:
          - asset: assets/fonts/Helvetica-Font/helvetica-light-587ebe5a59211.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash.png
    - assets/youtube.jpg
    - assets/animations/noInternet.json
    - assets/sidebar_line.png
    - assets/person_home.png
    - assets/UNAIS ACADEMY.png
    - assets/person_course.png
    - assets/account.jpg
    - assets/calender.png
    - assets/chart.png
    - assets/Check.png
    - assets/diagram.png
    - assets/Saved.png
    - assets/youtube_decerotion.png
    - assets/youtube.png
    - assets/icons/search.svg
    - assets/icons/pie_chart.png
    - assets/icons/home_logo.svg
    - assets/icons/sidebar.svg
    - assets/icons/get_in.svg
    - assets/animations/construction.json
    - assets/animations/done.json
    - assets/3dbg.png
    - assets/icons/Saved.png
    - assets/icons/Check.png
    - assets/icons/play.png
    - assets/icons/shopping-bag.svg
    - assets/design_el_1.png
    - assets/welcome.png
    - assets/play.png
    - assets/welcome_illustator.svg
  #   - images/a_dot_ham.jpeg

  
# assets:
  #   - assets/account_image.svg
  #   - assets/assets_group.svg
  #   - assets/person_course.svg
  #   - assets/person_home.svg
  #   - assets/top_right_design.svg
  #   - assets/UNAIS ACADEMY.svg
  #   - assets/welcome_illustator.svg
  #   #icons
  #   - assets/icons/arrow-left.svg
  #   - assets/icons/get_in.svg
  #   - assets/icons/green_check.svg
  #   - assets/icons/home_logo.svg
  #   - assets/icons/home.svg
  #   - assets/icons/menu.svg
  #   - assets/icons/more-vertical.svg
  #   - assets/icons/person.svg
  #   - assets/icons/play.svg
  #   - assets/icons/saved.svg
  #   - assets/icons/search.svg
  #   - assets/icons/shopping-bag.svg
  #   - assets/icons/sidebar_line.svg
  #   - assets/icons/sidebar.svg
  #   - assets/icons/star.svg
  #   #icon-logo
  #   - assets/icon-logo/calender.svg
  #   - assets/icon-logo/chart.svg
  #   - assets/icon-logo/diagram.svg
  #   - assets/icon-logo/youtube.svg
  #   #animations
  #   - assets/animations/40871-progress-bar-red.json
  #   - assets/animations/construction.json
  #   - assets/animations/done.json
  #   - assets/animations/noInternet.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
    
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
